[package]
name = "simple-gui"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "simple-gui"
path = "src/main.rs"

[dependencies]
backend-nmrs = { workspace = true }
connections-web = { workspace = true }

tokio = { version = "1.53.1", features = ["full"] }
axum = { version = "0.8.9", features = ["macros"] }
tower-http = { version = "0.6", features = ["fs"] }
